[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':(exclude)android/'"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
